import = ["~/.config/alacritty/themes/gruvbox_material_hard_dark.toml"]

# Window settings
[window]
opacity = 0.95
decorations = "Full"
padding = { x = 5, y = 5 }
dynamic_padding = true

# Font settings
[font]
size = 10.0
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
bold_italic = { family = "Fira Code", style = "Bold Italic" }
